config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  resources :users do
    resources :recipes, :recipe_ingredients do
      resources :ingredients, only: [:new, :create, :edit, :update]
    end
  end
  
  
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  post 'users/new', to: 'users#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :recipe_ingredients, dependent: :destroy
  has_many :ingredients, through: :recipe_ingredients
  accepts_nested_attributes_for :recipe_ingredients
  
  has_many :user_recipes, dependent: :destroy
  has_many :users, through: :user_recipes
  
  belongs_to :owner, class_name: 'User', foreign_key: 'owner_id'
  
  def recipe_ingredient
    RecipeIngredient.where(recipe_id: id)
  end
  
  def self.owned_recipes(id)
    where(owner_id: id)
  end
  
  def flours_amt(id)
    RecipeIngredient.select('ingredients.name')
      .joins(:ingredient)
      .where(recipe_id: id)
      .where('ingredients.name like ?', '%Flour%')
      .sum(:amount)
  end
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient

  def ing_name
    Ingredient.find(ingredient_id).name
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :username, presence: true, uniqueness: true
  has_many :user_recipes
  has_many :recipes, through: :user_recipes
end

app/models/user_recipe.rb
class UserRecipe < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  helper_method :current_user
  
  def current_user
    current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  
  def new
    @recipe = Recipe.find(params[:recipe_id])
    @ingredient = Ingredient.new
    @recipe_ingredient = RecipeIngredient.new
  end
  
  def create
    @recipe = Recipe.find(params[:recipe_id])
    @ingredient = Ingredient.find(params[:recipe_ingredient][:ingredient_id])
    @recipe_ingredient = RecipeIngredient.create(recipe_id: @recipe.id,
                                          ingredient_id: @ingredient.id,
                                          amount: params[:recipe_ingredient][:amount]
                                            )
    redirect_to user_recipe_path(current_user,@recipe)
  end  
  
  def edit
    @recipe_ingredient = RecipeIngredient.find(params[:recipe_ingredient_id])
    
  end
  
  def update
    @recipe = Recipe.find(params[:id])
    recipe_ingredient = RecipeIngredient.find(params[:recipe_id])
    recipe_ingredient.update(amount: params[:recipe_ingredient][:recipe_ingredients][:amount].to_f)
    # require "pry"; binding.pry
    redirect_to user_recipe_path(current_user,@recipe)
  end
  
  private
  
  def ingredient_params
    params.require(:ingredient).permit(:name, {:recipe_ids=>[]})
  end
end

app/controllers/recipe_ingredients_controller.rb
class RecipeIngredientsController < ApplicationController
  
  # def edit
  #   @recipe_ingredient = RecipeIngredient.find(params[:id])
  #   
  # end
  # 
  # def update
  #   @recipe = Recipe.find(params[:recipe_id])
  #   RecipeIngredient.update(recipe_ingredient_params)
  #   redirect_to recipe_path(@recipe)
  # end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  
  def index
    @recipes = Recipe.owned_recipes(params[:user_id])
  end
  
  def new
    @recipe = Recipe.new
  end
  
  def create
    @recipe = Recipe.create(recipe_params)
    redirect_to recipe_path(@recipe)
  end
  
  def show
    @recipe = Recipe.find(params[:id])
  end
  
  def edit
    @recipe = Recipe.find(params[:id])
    @recipe_ingredients = @recipe.recipe_ingredient
  end
  
  def update
    @recipe = Recipe.find(params[:id])
    @recipe.recipe_ingredients = RecipeIngredient.update_attributes(params[:recipe][:recipe_ingredients_attributes])
    redirect_to recipe_path(@recipe)
  end
  
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to user_recipes_path(current_user)
  end
  
  
  private
  
  def recipe_params
    params.require(:recipe).permit(:name,
                                   :recipe_ingredients_attributes => [:id, :amount],
                                   :ingredient_ids => [])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    
  end
  
  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to user_recipes_path(current_user)
    else
      # either user doesn't exist or wrong password sad path testing
    end
  end
  
  def destroy
    session.clear
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_recipes_path(current_user)
    else
      #rerender new view if validations don't pass
    end
  end
  
  def show
    # @user = current_user
  end
  
  def update
    # require "pry"; binding.pry
    recipe_name = params[:user][:recipes][:name]
    current_user.recipes << Recipe.create(name: recipe_name, owner_id: current_user.id)
    recipe_id = current_user.recipes.last.id
    redirect_to user_recipe_path(current_user, recipe_id)
  end
  
  private
  
  def user_params
    params.require(:user).permit(:username, :password, :recipes_attributes)
  end
end

app/views/ingredients/edit.html.erb
<h1>Edit Recipe</h1>
<%= form_for [current_user,@recipe_ingredient] do |recipe_form| %>
  <%= recipe_form.fields_for :recipe_ingredients do |f| %>
    <%= f.label :amount %>
    <%= f.number_field :amount, step: :any %>
    
    <%= f.submit "Update Amount" %>
  <% end %>
<% end %>

app/views/ingredients/new.html.erb
<h1>Add Ingredient</h1>

<%= form_for [current_user,@recipe_ingredient] do |f|%>
  <%= f.collection_select :ingredient_id, Ingredient.all, :id, :name %>

  <%= f.label :amount %>
  <%= f.number_field :amount, step: :any %>
  
  <%= f.submit 'Add Ingredient' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BakeShop</title>
    <%= csrf_meta_tags %>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          rel="stylesheet" 
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" 
          crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" 
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" 
            crossorigin="anonymous"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" 
          rel="stylesheet" 
          integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" 
          crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" 
            integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" 
            crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
      <% if current_user %>
        Welcome, <%= current_user.username %>!
         <%= button_to 'Logout', logout_path, method: :delete %>
      <% end %>
      <%= yield %>
      
  </body>
</html>

app/views/recipe_ingredients/edit.html.erb
<h1>Edit Recipe</h1>
<%= form_for @recipe, remote: true do |recipe_form| %>
  <%#= recipe_form.fields_for :recipe_ingredients do |f| %>
    <%= f.label :amount %>
    <%= f.number_field :amount, step: :any %>
    
    <%= f.submit %>
  <% end %>
<% end %>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>
<%= form_for @recipe, remote: true do |recipe_form| %>
  <%= recipe_form.fields_for :recipe_ingredients do |f| %>
    <%= f.label :amount %>
    <%= f.number_field :amount, step: :any %>
    
    <%= f.submit %>
  <% end %>
<% end %>

app/views/recipes/index.html.erb
<div class="">
  
  <h1>All Recipes</h1>

  <ul>
    <% @recipes.each do |recipe| %>
      <li>
        <%= link_to recipe.name, user_recipe_path(current_user, recipe) %>
        <%= button_to 'Delete', user_recipe_path(current_user, recipe), method: :delete%>
      </li>
    <% end %>
  </ul>

</div>
<%= link_to 'Add Recipe', new_user_recipe_path(current_user) %>

app/views/recipes/new.html.erb
<h1> New Recipe </h1>

<%= form_for(current_user) do |recipe_form| %>
  <%= recipe_form.fields_for :recipes do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    
    <%= f.submit 'Create Recipe' %>
  <% end %>
<% end %>

app/views/recipes/show.html.erb
  
  <h1><%= @recipe.name %> Recipe</h1>
        <table>
          <tr>
            <th>Ingredient Name</th>
            <th>Amount in ounces</th>
          </tr>
            <% @recipe.recipe_ingredients.each do |recipe_ingredient| %>
            <tbody>
            <tr>
              <td><%= recipe_ingredient.ing_name %></td>
              <td><%= recipe_ingredient.amount %><br> <%= link_to 'Edit Ingredient',
                        edit_user_recipe_ingredient_ingredient_path(current_user,recipe_ingredient) %> </td>
            </tr>
          </tbody>
            <% end %>
        </table>

<%= link_to 'Add Ingredient', new_user_recipe_ingredient_path(current_user, @recipe) %><br><br>
<%= link_to '<< Back to Recipes', user_recipes_path(current_user) %>

app/views/users/new.html.erb
<h1>Create New Account </h1>

<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %><br>
  
  <%= f.label :password %>
  <%= f.password_field :password %><br>
  
  <%= f.submit 'Create Account' %>
<% end %>